source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'RongCloudSingleChat' do
    pod 'RongCloudIM/IMLib', '~> 2.8.14'
    pod 'RongCloudIM/IMKit', '~> 2.8.14'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'Mantle', '~> 2.1.0'
    pod 'FMDB', '~> 2.7.2'
end
